language: ruby

before_install: gem install bundler

before_script:
  - cd spec/dummy_app
  - bundle exec rake db:create db:migrate
  - cd ../../

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

cache: bundler

rvm:
  - 2.3.1
