# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d838330ecf3e32552a2a68828d67b74cca8ecb503a5445bcebac14535ab14b008752d09ac3a1d544450bea5bb5b2c89b44688e79899b4cc42633356012d9ea43

test:
  secret_key_base: 8c3e0333b07323d884cfaf1bf4c9814c629a559a2016cee20b0599880c774b0a441faf73c7e55feba5dc113b3d4dcf5b12b748c394bdbc676290d1bf8909226f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
